server:
  port: 8080

spring:
  application:
    name: api-gateway

spring.cloud.gateway:
  routes:
    - id: product-service
      uri: http://localhost:8081
      predicates:
        - Path=/products/**
    - id: client-service
      uri: http://localhost:8082
      predicates:
        - Path=/clients/**
    - id: order-service
      uri: http://localhost:8083
      predicates:
        - Path=/orders/**
