server:
  port: 8080

spring:
  application:
    name: api-gateway

# ????????? ?????????????
spring.cloud.gateway:
  routes:
    - id: client-service-route
      uri: lb://client-service  # ????? ????????????
      predicates:
        - Path=/clients/**    # ???? ???????
    - id: order-service-route
      uri: lb://order-service
      predicates:
        - Path=/orders/**
