server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
